#spring:
#  datasource:
#    url: jdbc:mariadb://47.100.61.46:3306/game
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: game_admin
#    password: Game414371114
#
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/game
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
